export interface AnalyticsPeriodQuery { readonly from: string; readonly to: string; }
export interface AnalyticsOverviewResponse { readonly from: string; readonly to: string; readonly membership: { readonly totalMembers: number; readonly activeMembers: number; readonly newMembers: number; readonly suspendedMembers: number; readonly closedMembers: number }; readonly activity: { readonly receiptCount: number; readonly qualifyingReceiptCount: number; readonly qualifyingPurchaseAmount: readonly { readonly currency: string; readonly amountMinor: number }[] }; readonly rewardPoints: { readonly pointsEarned: number; readonly pointsRedeemed: number; readonly pointsExpired: number }; readonly redemption: { readonly redemptionCount: number; readonly redemptionPoints: number; readonly uniqueRedeemingMembers: number }; readonly engagement: { readonly activeMembersWithActivity: number; readonly earningMembers: number; readonly redeemingMembers: number }; readonly statusDistribution: readonly { readonly statusLevelId: string; readonly memberCount: number }[]; }

export class AnalyticsContractValidationError extends Error { constructor(readonly field: string, message: string) { super(`${field}: ${message}`); this.name = "AnalyticsContractValidationError"; } }
function record(value: unknown, field: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new AnalyticsContractValidationError(field, "must be an object"); return value as Record<string, unknown>; }
function exact(input: Record<string, unknown>, fields: readonly string[], field: string): void { for (const key of Object.keys(input)) if (!fields.includes(key)) throw new AnalyticsContractValidationError(`${field}.${key}`, "is not allowed"); }
function text(value: unknown, field: string): string { if (typeof value !== "string" || value.trim() === "") throw new AnalyticsContractValidationError(field, "must be non-empty"); return value.trim(); }
function utc(value: unknown, field: string): string { const result = text(value, field); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(result) || Number.isNaN(Date.parse(result))) throw new AnalyticsContractValidationError(field, "must be canonical UTC"); return result; }
function count(value: unknown, field: string): number { if (!Number.isSafeInteger(value) || (value as number) < 0) throw new AnalyticsContractValidationError(field, "must be a non-negative integer"); return value as number; }

export function validateAnalyticsPeriodQuery(value: unknown): AnalyticsPeriodQuery { const input = record(value, "query"); exact(input, ["from", "to"], "query"); const from = utc(input.from, "query.from"); const to = utc(input.to, "query.to"); if (from >= to) throw new AnalyticsContractValidationError("query", "from must precede to"); return { from, to }; }
export function validateAnalyticsOverviewResponse(value: unknown): AnalyticsOverviewResponse {
  const input = record(value, "response"); exact(input, ["from", "to", "membership", "activity", "rewardPoints", "redemption", "engagement", "statusDistribution"], "response");
  const membership = record(input.membership, "membership"); exact(membership, ["totalMembers", "activeMembers", "newMembers", "suspendedMembers", "closedMembers"], "membership");
  const activity = record(input.activity, "activity"); exact(activity, ["receiptCount", "qualifyingReceiptCount", "qualifyingPurchaseAmount"], "activity");
  const rewardPoints = record(input.rewardPoints, "rewardPoints"); exact(rewardPoints, ["pointsEarned", "pointsRedeemed", "pointsExpired"], "rewardPoints");
  const redemption = record(input.redemption, "redemption"); exact(redemption, ["redemptionCount", "redemptionPoints", "uniqueRedeemingMembers"], "redemption");
  const engagement = record(input.engagement, "engagement"); exact(engagement, ["activeMembersWithActivity", "earningMembers", "redeemingMembers"], "engagement");
  const amounts = activity.qualifyingPurchaseAmount;
  if (!Array.isArray(amounts)) throw new AnalyticsContractValidationError("activity.qualifyingPurchaseAmount", "must be an array");
  const currencies = new Set<string>();
  const qualifyingPurchaseAmount = amounts.map((amount, index) => { const item = record(amount, `activity.qualifyingPurchaseAmount[${index}]`); exact(item, ["currency", "amountMinor"], `activity.qualifyingPurchaseAmount[${index}]`); const currency = text(item.currency, `activity.qualifyingPurchaseAmount[${index}].currency`).toUpperCase(); if (!/^[A-Z]{3}$/u.test(currency)) throw new AnalyticsContractValidationError("currency", "must be ISO 4217"); if (currencies.has(currency)) throw new AnalyticsContractValidationError("currency", "must be unique"); currencies.add(currency); return { currency, amountMinor: count(item.amountMinor, `activity.qualifyingPurchaseAmount[${index}].amountMinor`) }; });
  const distribution = input.statusDistribution; if (!Array.isArray(distribution)) throw new AnalyticsContractValidationError("statusDistribution", "must be an array");
  const statusDistribution = distribution.map((item, index) => { const entry = record(item, `statusDistribution[${index}]`); exact(entry, ["statusLevelId", "memberCount"], `statusDistribution[${index}]`); return { statusLevelId: text(entry.statusLevelId, "statusLevelId"), memberCount: count(entry.memberCount, "memberCount") }; });
  const result = { from: utc(input.from, "from"), to: utc(input.to, "to"), membership: { totalMembers: count(membership.totalMembers, "totalMembers"), activeMembers: count(membership.activeMembers, "activeMembers"), newMembers: count(membership.newMembers, "newMembers"), suspendedMembers: count(membership.suspendedMembers, "suspendedMembers"), closedMembers: count(membership.closedMembers, "closedMembers") }, activity: { receiptCount: count(activity.receiptCount, "receiptCount"), qualifyingReceiptCount: count(activity.qualifyingReceiptCount, "qualifyingReceiptCount"), qualifyingPurchaseAmount }, rewardPoints: { pointsEarned: count(rewardPoints.pointsEarned, "pointsEarned"), pointsRedeemed: count(rewardPoints.pointsRedeemed, "pointsRedeemed"), pointsExpired: count(rewardPoints.pointsExpired, "pointsExpired") }, redemption: { redemptionCount: count(redemption.redemptionCount, "redemptionCount"), redemptionPoints: count(redemption.redemptionPoints, "redemptionPoints"), uniqueRedeemingMembers: count(redemption.uniqueRedeemingMembers, "uniqueRedeemingMembers") }, engagement: { activeMembersWithActivity: count(engagement.activeMembersWithActivity, "activeMembersWithActivity"), earningMembers: count(engagement.earningMembers, "earningMembers"), redeemingMembers: count(engagement.redeemingMembers, "redeemingMembers") }, statusDistribution };
  if (result.from >= result.to) throw new AnalyticsContractValidationError("response", "from must precede to");
  return Object.freeze(result);
}
