export type ReceiptStatus = "ACCEPTED" | "CANCELLED";
export interface RecordReceiptRequest { readonly membershipToken: string; readonly locationId: string; readonly receiptNumber: string; readonly sourceId: string; readonly amountMinor: number; readonly currency: string; readonly receiptTimestamp: string; readonly idempotencyKey: string; }
export interface CancelReceiptRequest { readonly reason: string; readonly locationId: string; readonly idempotencyKey: string; }
export class ReceiptContractValidationError extends Error { constructor(readonly field: string, message: string) { super(`${field}: ${message}`); this.name = "ReceiptContractValidationError"; } }
function record(value: unknown): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new ReceiptContractValidationError("request", "must be an object"); return value as Record<string, unknown>; }
function exact(input: Record<string, unknown>, fields: readonly string[]): void { for (const field of Object.keys(input)) if (!fields.includes(field)) throw new ReceiptContractValidationError(field, "is not allowed"); }
function text(value: unknown, field: string): string { if (typeof value !== "string" || value.trim() === "") throw new ReceiptContractValidationError(field, "must be non-empty"); return value.trim(); }
function timestamp(value: unknown, field: string): string { const result = text(value, field); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(result) || Number.isNaN(Date.parse(result))) throw new ReceiptContractValidationError(field, "must be canonical UTC"); return result; }
export function validateRecordReceiptRequest(value: unknown): RecordReceiptRequest { const input = record(value); exact(input, ["membershipToken", "locationId", "receiptNumber", "sourceId", "amountMinor", "currency", "receiptTimestamp", "idempotencyKey"]); if (!Number.isSafeInteger(input.amountMinor) || (input.amountMinor as number) < 0) throw new ReceiptContractValidationError("amountMinor", "must be a non-negative integer minor-unit amount"); const currency = text(input.currency, "currency").toUpperCase(); if (!/^[A-Z]{3}$/u.test(currency)) throw new ReceiptContractValidationError("currency", "must be an ISO 4217 code"); return { membershipToken: text(input.membershipToken, "membershipToken"), locationId: text(input.locationId, "locationId"), receiptNumber: text(input.receiptNumber, "receiptNumber"), sourceId: text(input.sourceId, "sourceId"), amountMinor: input.amountMinor as number, currency, receiptTimestamp: timestamp(input.receiptTimestamp, "receiptTimestamp"), idempotencyKey: text(input.idempotencyKey, "idempotencyKey") }; }
export function validateCancelReceiptRequest(value: unknown): CancelReceiptRequest { const input = record(value); exact(input, ["reason", "locationId", "idempotencyKey"]); return { reason: text(input.reason, "reason"), locationId: text(input.locationId, "locationId"), idempotencyKey: text(input.idempotencyKey, "idempotencyKey") }; }
