export const REWARD_LEDGER_TRANSACTION_TYPES = ["EARNED", "PENDING", "RELEASED", "RESERVED", "RESERVATION_RELEASED", "REDEEMED", "REDEMPTION_CANCELLED", "EXPIRED", "REVERSED"] as const;
export type RewardLedgerTransactionType = (typeof REWARD_LEDGER_TRANSACTION_TYPES)[number];
export interface RewardLedgerTransaction { readonly id: string; readonly membershipId: string; readonly rewardAccountId: string; readonly activityId: string; readonly earningDecisionId: string; readonly loyaltyProgramId: string; readonly programConfigurationVersionId: string; readonly type: RewardLedgerTransactionType; readonly points: bigint; readonly occurredAt: string; readonly idempotencyKey: string; }
export interface RewardAccountProjection { readonly available: bigint; readonly pending: bigint; readonly reserved: bigint; readonly redeemed: bigint; readonly expired: bigint; readonly reversed: bigint; readonly total: bigint; }
export class RewardLedgerValidationError extends Error { constructor(readonly code: "INPUT_INVALID" | "IMMUTABLE_HISTORY", message: string) { super(message); this.name = "RewardLedgerValidationError"; } }
function id(value: unknown, field: string): string { if (typeof value !== "string" || value.trim() === "") throw new RewardLedgerValidationError("INPUT_INVALID", `${field} must be non-empty`); return value.trim(); }
function utc(value: unknown): string { const result = id(value, "occurredAt"); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(result) || Number.isNaN(Date.parse(result))) throw new RewardLedgerValidationError("INPUT_INVALID", "occurredAt must be canonical UTC"); return result; }
export function createRewardLedgerTransaction(input: Omit<RewardLedgerTransaction, "id"> & { readonly id: string }): RewardLedgerTransaction { if (!REWARD_LEDGER_TRANSACTION_TYPES.includes(input.type)) throw new RewardLedgerValidationError("INPUT_INVALID", "unsupported transaction type"); if (typeof input.points !== "bigint" || input.points <= 0n) throw new RewardLedgerValidationError("INPUT_INVALID", "points must be a positive whole number"); return Object.freeze({ id: id(input.id, "id"), membershipId: id(input.membershipId, "membershipId"), rewardAccountId: id(input.rewardAccountId, "rewardAccountId"), activityId: id(input.activityId, "activityId"), earningDecisionId: id(input.earningDecisionId, "earningDecisionId"), loyaltyProgramId: id(input.loyaltyProgramId, "loyaltyProgramId"), programConfigurationVersionId: id(input.programConfigurationVersionId, "programConfigurationVersionId"), type: input.type, points: input.points, occurredAt: utc(input.occurredAt), idempotencyKey: id(input.idempotencyKey, "idempotencyKey") }); }
export function projectRewardAccount(transactions: readonly RewardLedgerTransaction[]): RewardAccountProjection { const result = { available: 0n, pending: 0n, reserved: 0n, redeemed: 0n, expired: 0n, reversed: 0n }; for (const transaction of transactions) { if (transaction.type === "EARNED" || transaction.type === "RELEASED" || transaction.type === "REDEMPTION_CANCELLED" || transaction.type === "RESERVATION_RELEASED") result.available += transaction.points; if (transaction.type === "PENDING") result.pending += transaction.points; if (transaction.type === "RESERVED") { result.available -= transaction.points; result.reserved += transaction.points; } if (transaction.type === "REDEEMED") { result.reserved -= transaction.points; result.redeemed += transaction.points; } if (transaction.type === "EXPIRED") { result.available -= transaction.points; result.expired += transaction.points; } if (transaction.type === "REVERSED") { result.available -= transaction.points; result.reversed += transaction.points; } } return Object.freeze({ ...result, total: result.available + result.pending + result.reserved }); }
