import { createRewardLedgerTransaction, type RewardLedgerTransaction } from "./reward-ledger.js";
import type { PendingAndExpirationConfiguration } from "../loyalty-program/reward-policy.js";

export interface RewardLifecycleContext { readonly earningDecisionId: string; readonly activityId: string; readonly membershipId: string; readonly rewardAccountId: string; readonly loyaltyProgramId: string; readonly programConfigurationVersionId: string; readonly points: bigint; readonly occurredAt: string; readonly idempotencyKey: string; }
export class RewardLifecycleError extends Error { constructor(readonly code: "INPUT_INVALID" | "NOT_ELIGIBLE", message: string) { super(message); this.name = "RewardLifecycleError"; } }
function day(value: string): Date { const date = new Date(value); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(value) || Number.isNaN(date.getTime())) throw new RewardLifecycleError("INPUT_INVALID", "timestamp must be canonical UTC"); return date; }
function iso(date: Date): string { return date.toISOString(); }
function transitionId(context: RewardLifecycleContext, type: string, at: string): string { return `${context.earningDecisionId}:${type}:${at}`; }
export function createEarningLifecycleTransaction(context: RewardLifecycleContext, policy: PendingAndExpirationConfiguration): RewardLedgerTransaction { const occurred = day(context.occurredAt); const pending = policy.pendingDays > 0; return createRewardLedgerTransaction({ id: transitionId(context, pending ? "PENDING" : "EARNED", context.occurredAt), membershipId: context.membershipId, rewardAccountId: context.rewardAccountId, activityId: context.activityId, earningDecisionId: context.earningDecisionId, loyaltyProgramId: context.loyaltyProgramId, programConfigurationVersionId: context.programConfigurationVersionId, type: pending ? "PENDING" : "EARNED", points: context.points, occurredAt: iso(occurred), idempotencyKey: `${context.idempotencyKey}:initial` }); }
export function releasePendingPoints(context: RewardLifecycleContext, policy: PendingAndExpirationConfiguration, evaluationTime: string, existing: readonly RewardLedgerTransaction[] = []): RewardLedgerTransaction | null { const evaluated = day(evaluationTime); const eligible = new Date(context.occurredAt).getTime() + policy.pendingDays * 86400000 <= evaluated.getTime(); if (!eligible) return null; const id = transitionId(context, "RELEASED", context.occurredAt); if (existing.some((transaction) => transaction.id === id)) return null; return createRewardLedgerTransaction({ id, membershipId: context.membershipId, rewardAccountId: context.rewardAccountId, activityId: context.activityId, earningDecisionId: context.earningDecisionId, loyaltyProgramId: context.loyaltyProgramId, programConfigurationVersionId: context.programConfigurationVersionId, type: "RELEASED", points: context.points, occurredAt: iso(evaluated), idempotencyKey: `${context.idempotencyKey}:release` }); }
export function expireAvailablePoints(context: RewardLifecycleContext, policy: PendingAndExpirationConfiguration, evaluationTime: string, existing: readonly RewardLedgerTransaction[] = []): RewardLedgerTransaction | null { const evaluated = day(evaluationTime); if (policy.expiration.mode === "NONE") return null; const base = new Date(context.occurredAt); const expiration = policy.expiration.mode === "ROLLING" ? new Date(base.getTime() + policy.expiration.days * 86400000) : new Date(Date.UTC(base.getUTCFullYear() + ((base.getUTCMonth() + 1 > policy.expiration.month || (base.getUTCMonth() + 1 === policy.expiration.month && base.getUTCDate() >= policy.expiration.day)) ? 1 : 0), policy.expiration.month - 1, policy.expiration.day)); if (evaluated.getTime() < expiration.getTime()) return null; const id = transitionId(context, "EXPIRED", iso(expiration)); if (existing.some((transaction) => transaction.id === id)) return null; return createRewardLedgerTransaction({ id, membershipId: context.membershipId, rewardAccountId: context.rewardAccountId, activityId: context.activityId, earningDecisionId: context.earningDecisionId, loyaltyProgramId: context.loyaltyProgramId, programConfigurationVersionId: context.programConfigurationVersionId, type: "EXPIRED", points: context.points, occurredAt: iso(expiration), idempotencyKey: `${context.idempotencyKey}:expire` }); }
