import assert from "node:assert/strict";
import test from "node:test";
import { calculateBusinessObservation } from "../dist/modules/analytics/business-observation.js";
import { createRewardLedgerTransaction } from "../dist/modules/reward/reward-ledger.js";

const period = { from: "2026-08-01T00:00:00.000Z", to: "2026-08-08T00:00:00.000Z" };
const memberships = [
  { id: "m-1", loyaltyProgramId: "program-1", createdAt: "2026-08-02T00:00:00.000Z", statusHistory: [{ status: "ACTIVE", occurredAt: "2026-08-02T00:00:00.000Z" }], statusLevelHistory: [{ statusLevelId: "silver", occurredAt: "2026-08-02T00:00:00.000Z" }] },
  { id: "m-2", loyaltyProgramId: "program-1", createdAt: "2026-07-01T00:00:00.000Z", statusHistory: [{ status: "ACTIVE", occurredAt: "2026-07-01T00:00:00.000Z" }, { status: "SUSPENDED", occurredAt: "2026-08-06T00:00:00.000Z" }], statusLevelHistory: [{ statusLevelId: "gold", occurredAt: "2026-07-01T00:00:00.000Z" }] },
  { id: "m-3", loyaltyProgramId: "program-1", createdAt: "2026-07-01T00:00:00.000Z", statusHistory: [{ status: "CLOSED", occurredAt: "2026-07-01T00:00:00.000Z" }], statusLevelHistory: [] },
];
const receipt = { id: "receipt-1", loyaltyProgramId: "program-1", membershipId: "m-1", occurredAt: "2026-08-03T10:00:00.000Z", qualifying: true, amountMinor: 1250n, currency: "EUR" };
const ledger = createRewardLedgerTransaction({ id: "earned-1", membershipId: "m-1", rewardAccountId: "a-1", activityId: "receipt-1", earningDecisionId: "decision-1", loyaltyProgramId: "program-1", programConfigurationVersionId: "version-3", type: "EARNED", points: 100n, occurredAt: "2026-08-03T10:00:01.000Z", idempotencyKey: "earned-1" });
const redemption = { id: "redemption-1", loyaltyProgramId: "program-1", membershipId: "m-1", status: "CONFIRMED", points: 40n, occurredAt: "2026-08-04T10:00:00.000Z", programConfigurationVersionId: "version-3" };

test("calculates membership, activity, reward, redemption, engagement, and status metrics", () => { const result = calculateBusinessObservation({ period, loyaltyProgramId: "program-1", memberships, receipts: [receipt], rewardLedger: [ledger], redemptions: [redemption] }); assert.deepEqual(result.membership, { totalMembers: 3, activeMembers: 1, newMembers: 1, suspendedMembers: 1, closedMembers: 1 }); assert.deepEqual(result.activity, { receiptCount: 1, qualifyingReceiptCount: 1, qualifyingPurchaseAmount: [{ currency: "EUR", amountMinor: 1250n }] }); assert.deepEqual(result.rewardPoints, { pointsEarned: 100n, pointsRedeemed: 40n, pointsExpired: 0n }); assert.deepEqual(result.redemption, { redemptionCount: 1, redemptionPoints: 40n, uniqueRedeemingMembers: 1 }); assert.deepEqual(result.engagement, { activeMembersWithActivity: 1, earningMembers: 1, redeemingMembers: 1 }); assert.deepEqual(result.statusDistribution, [{ statusLevelId: "gold", memberCount: 1 }, { statusLevelId: "silver", memberCount: 1 }]); });
test("uses half-open windows, separates currencies, and de-duplicates idempotent inputs", () => { const boundary = { ...receipt, id: "receipt-boundary", occurredAt: period.to }; const otherCurrency = { ...receipt, id: "receipt-usd", currency: "USD", amountMinor: 200n }; const result = calculateBusinessObservation({ period, loyaltyProgramId: "program-1", memberships, receipts: [receipt, receipt, boundary, otherCurrency], rewardLedger: [ledger, ledger], redemptions: [redemption, redemption] }); assert.equal(result.activity.receiptCount, 2); assert.deepEqual(result.activity.qualifyingPurchaseAmount, [{ currency: "EUR", amountMinor: 1250n }, { currency: "USD", amountMinor: 200n }]); assert.equal(result.rewardPoints.pointsEarned, 100n); assert.equal(result.redemption.redemptionCount, 1); });
test("returns zero data and never exposes Customer PII", () => { const result = calculateBusinessObservation({ period, loyaltyProgramId: "program-1", memberships: [], receipts: [], rewardLedger: [], redemptions: [] }); assert.deepEqual(result, { membership: { totalMembers: 0, activeMembers: 0, newMembers: 0, suspendedMembers: 0, closedMembers: 0 }, activity: { receiptCount: 0, qualifyingReceiptCount: 0, qualifyingPurchaseAmount: [] }, rewardPoints: { pointsEarned: 0n, pointsRedeemed: 0n, pointsExpired: 0n }, redemption: { redemptionCount: 0, redemptionPoints: 0n, uniqueRedeemingMembers: 0 }, engagement: { activeMembersWithActivity: 0, earningMembers: 0, redeemingMembers: 0 }, statusDistribution: [] }); assert.equal(JSON.stringify(result, (_, value) => typeof value === "bigint" ? value.toString() : value).includes("phone"), false); });
test("does not recalculate historical outcomes from current configuration", () => { const result = calculateBusinessObservation({ period, loyaltyProgramId: "program-1", memberships, receipts: [], rewardLedger: [{ ...ledger, programConfigurationVersionId: "version-3", points: 100n }], redemptions: [] }); assert.equal(result.rewardPoints.pointsEarned, 100n); });
